Add autocomplete_allow_unpublished attribute to target model to allow unpublished pages to be returned by search
wagtail/wagtail-autocomplete pull request #135
Opened 2022-12-20 19:45 UTC by tbock

This skips returning live and returns the base queryset instead.

2023-01-19 20:42 UTC, harrislapiroff commented
Thanks, @tbock! We'll look over this feature soon.

2023-01-30 04:21 UTC, SaptakS requested changes
@tbock the code mostly looks good to me. Can you also add documentation about this feature as part of this PR? You can find the list of things we usually need before merging a PR in our [Contribution Guidelines](https://wagtail-autocomplete.readthedocs.io/en/latest/contributing.html)

2024-03-08 00:05 UTC, pcraciunoiu commented
Before finding this PR, I took another approach here: #182.

Happy to go with either approach and take this feature over the finish line, if anyone is willing to review it

2026-07-06 10:01 UTC, SaptakS commented
@tbock #182 has been merged and  I think that solves the requirements of this PR. Closing but please reopen it if you think its wrong.

2026-07-06 10:01 UTC, closed without merging